### ISSUE TITLE
examples of use

### ISSUE THREAD

**Issue by NuriaQueralt** [tkonopka/NetworkCurator#1]
Dear NetworkCurator team,

I am exploring the use of NetworkCurator.  I was wondering if there is any example site that is already  using it like the one you pointed at Example site: https://www.screensignatures.org/

Many thanks in advance!

**Comment by tkonopka** [comment]
Hi Nuria, thanks for your inquiry. Unfortunately, the example site screensignatures.org is no longer active and I'm not aware of others. I would be happy to respond to any questions you may have about the software, though.
